.\" start of Projects
.sec
Projects
.reg
.br .\"line break

.KS
.ssec "Weather Guide (HTML, CSS & JavaScript - Bootstrap)"
.br
.small
A simple weather forecasting Web App.
.KE

.KS
.ssec "Summaritizer (HTML, CSS & JavaScript - Bulma CSS, Python)"
.br
.small
A simple Web App for sharing notes and ideas with friends in markdown format. 
.KE

.KS
.ssec "Blogarithm (HTML, CSS & JavaScript - Bulma CSS, Python - Flask)"
.br .\" line break
.small
A small and simple blog site. (In Development)
.KE
